### PR TITLE
refactor to build with browserify

### PR DESCRIPTION
**Pull request by stephenmathieson**
- move dep management to npm
- move js build to browserify
- move css build to postcss (no need now, but maybe in the future? this could just be `cp` haha)

/cc @jwerle

### CODE REVIEW

**Comment by stephenmathieson** [comment]
i don't fully understand the purpose of `dist` vs `build` here. i'm tempted to remove `build` all together...

**Comment by jwerle** [comment]
@stephenmathieson yeah, agreed. It was more for folks who don't use package managers, but we don't need it any more

**Comment by jwerle** [comment]
LGTM!

**Comment by stephenmathieson** [comment]
right on. ill open a cleanup/etc pr soon

**Pull request merged**
